package main

import (
	"Cinema/api"
	"Cinema/utils"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
	"log"
)

func main() {
	config, err := utils.LoadConfig(".")
	if err != nil {
		log.Fatal(err)
	}
	server := api.NewServer()
	server.StartServer(":" + config.Port)
}
