// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Drink struct {
	ID       int64  `json:"id"`
	DrinkID  string `json:"drink_id"`
	Name     string `json:"name"`
	Price    int64  `json:"price"`
	ImageUrl string `json:"image_url"`
}

type Food struct {
	ID       int64  `json:"id"`
	FoodID   string `json:"food_id"`
	Name     string `json:"name"`
	Price    int64  `json:"price"`
	ImageUrl string `json:"image_url"`
}

type Movie struct {
	ID        int64  `json:"id"`
	MovieID   string `json:"movie_id"`
	MovieName string `json:"movie_name"`
	Runtime   int32  `json:"runtime"`
	Genre     string `json:"genre"`
	Status    string `json:"status"`
	ImageUrl  string `json:"image_url"`
}

type Order struct {
	ID        int64     `json:"id"`
	OrderID   string    `json:"order_id"`
	CreatedAt time.Time `json:"created_at"`
}

type OrderDrink struct {
	ID      int64  `json:"id"`
	OrderID string `json:"order_id"`
	DrinkID string `json:"drink_id"`
}

type OrderFood struct {
	ID      int64  `json:"id"`
	OrderID string `json:"order_id"`
	FoodID  string `json:"food_id"`
}

type Room struct {
	ID       int64  `json:"id"`
	RoomID   string `json:"room_id"`
	RoomName string `json:"room_name"`
	Active   bool   `json:"active"`
}

type Schedule struct {
	ID         int64     `json:"id"`
	ScheduleID string    `json:"schedule_id"`
	MovieID    string    `json:"movie_id"`
	RoomID     string    `json:"room_id"`
	TimeStart  time.Time `json:"time_start"`
	TimeEnd    time.Time `json:"time_end"`
}

type ScheduleTier struct {
	ID         int64  `json:"id"`
	ScheduleID string `json:"schedule_id"`
	TierID     string `json:"tier_id"`
	Price      int64  `json:"price"`
}

type Seat struct {
	ID     int64  `json:"id"`
	SeatID string `json:"seat_id"`
	RoomID string `json:"room_id"`
	TierID string `json:"tier_id"`
	Row    string `json:"row"`
	Column int32  `json:"column"`
	Active bool   `json:"active"`
}

type Ticket struct {
	ID         sql.NullInt64  `json:"id"`
	TicketID   string         `json:"ticket_id"`
	ScheduleID string         `json:"schedule_id"`
	OrderID    sql.NullString `json:"order_id"`
}

type TicketSeat struct {
	ID       int64  `json:"id"`
	TicketID string `json:"ticket_id"`
	SeatID   string `json:"seat_id"`
}

type Tier struct {
	ID       int64  `json:"id"`
	TierID   string `json:"tier_id"`
	TierName string `json:"tier_name"`
}

type User struct {
	ID        int64  `json:"id"`
	UserID    string `json:"user_id"`
	UserName  string `json:"user_name"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Password  string `json:"password"`
	Role      string `json:"role"`
}
